config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root :to => "reviews#index"
  resources :albumreviews, :except => ['create']
  resources :bookreviews do # NHO: Why did you need these custom route defintions and not resources :comments?
    get 'comments/new', to: 'comments#new_book_comment'
    post 'comments/post', to: 'comments#post_book_comment'
    delete 'comments/:id', to: 'comments#destroy_book_comment'
  end
  resources :reviews do
    resources :comments, :except => ['index', 'show']
  end
  get 'works/:id/show', to: 'works#show'  # NHO: What are purpose of these two custom routes for works?
  get 'works/:work_id/:work_index', to: 'works#select'
  resources :works do
    resources :albumreviews, :except => ['index', 'destroy' , 'show', 'edit', 'update']
  end
end

app/controllers/bookreviews_controller.rb
class BookreviewsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  # NHO: How could you DRY up this code? I see an opportunity for something along the lines of before_action :find_book_review
  # NHO: In general, Rails style guides advise Fat Models, Skinny Controllers.
  # NHO: I would advise to simplify controller code by moving our main business logic to our models
  # NHO: would recommend creating custom models or methods on existing models to help simplify
  def index
    #all book reviews for the index
    @bookreviews = Bookreview.all
  end
  def show
    #select a specific review for the show page
    @bookreview = Bookreview.find(params[:id])
    @comments = @bookreview.comments #select comments
    @info = Bookwork.find(@bookreview.bookwork_id) #info will be the api response from goodreads, which is stored in the the booksworks table in the db
    #this is a lsit of all books by the author in question, for display on the
    #show page

    # NHO: consider moving your api calls into seperate classes, so you can utilize them like models.
    @book_list = HTTParty.get("https://www.goodreads.com/author/list/#{@info.author_id}?format=xml&key=#{ENV['goodread_key']}")['GoodreadsResponse']['author']['books']['book']
  end
  def new
    #placeholder review
    @bookreview = Bookreview.new
  end
  def create
    #create a new review
    @bookreview = current_user.bookreviews.new(review_params)
    #make an api call based on the title of the book
    book_info = HTTParty.get("https://www.goodreads.com/search.xml?key=#{ENV['goodread_key']}&q=#{@bookreview.name.gsub(' ', '+')}")['GoodreadsResponse']['search']['results']['work'][0]['best_book']
    #create a new work, add information fromt he api call to the new work
    #I used the unique id to see if I already have this book in my DB.
    @new_work = Bookwork.find_or_create_by(unique_id: book_info['id']) # NHO: nice use of find_or_create_by!
    #if I didn't have the book, AKA the bookwork title column is empty, I need to fill up the new work object
    if (!@new_work.title)
      @new_work.update(unique_id: book_info['id'], image_url: book_info['image_url'], title: book_info['title'], author: book_info['author']['name'], author_id: book_info['author']['id'])
    end
    #add some information from the bookwork table to the review table, for easier access.
    #I don't think this was necessary
    @bookreview.update(bookwork_id: @new_work.id, category: "Book", photo_url: @new_work.image_url)
    #check to see if it saves and flash messages
    if @bookreview.save
      flash[:notice] = "Review was successfully created."
        redirect_to @bookreview
    else
      flash[:alert] = "Review creation failed, likely missing a needed field."
      render :new
    end
  end
  def destroy
    #destroy a specific review
    @bookreview = Bookreview.find(params[:id])
    @bookreview.destroy
    redirect_to bookreviews_path
  end
  def edit
    #select a review to edit
    @bookreview = Bookreview.find(params[:id])
  end
  def update
    #update a new review based on user input params
    @bookreview = Bookreview.find(params[:id])
    @bookreview.update(review_params)
    redirect_to bookreview_path(@bookreview)
  end
  private
  #strong params
  def review_params
    params.require(:bookreview).permit(:text, :title, :score, :name)
  end
end

app/views/bookreviews/_comments.html.erb
<div class="title">
  <%@comments.each do |comment|%>
    <h3>
      <%=comment.title%>
    </h3>
    <p>
      <%=comment.text%>
    </p>
    <p class="ital">
      By <%=comment.user.email%>
    </p>
    <%if current_user == @bookreview.user || current_user == comment.user%>
      <%=link_to "(Remove Comment)", "/bookreviews/#{@bookreview.id}/comments/#{comment.id}", :method => :delete%>
    <%end%>
    <hr>
  <%end%>
</div>

app/views/bookreviews/edit.html.erb
<div class="title">
  <h2>Edit Book Review</h2>
  <%=form_for @bookreview do |f| %>
  
    <%=f.label "Review Title"%><br>
    <%=f.text_field :title%><br>

    <%=f.label :score%><br>
    <%=f.select :score, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %><br>

    <%=f.label :text%><br>
    <%=f.text_area :text, rows: 3, cols: 30%><br>

    <%=f.submit%>
  <%end%>
</div>

app/views/bookreviews/index.html.erb
<!-- NHO: seeing a lot of similarity between reviews index pages, is there are a way to abstract them out using partials?  -->
<h2 class="title">
  All Book Reviews
  <%=link_to "(+)", new_bookreview_path%>
</h2>
<ul>
  <%@bookreviews.each do |review|%>
    <div class="booklist">
      <li>
        <a href=<%="/bookreviews/#{review.id}"%>> <!-- NHO: Could we utilize rails link_to helpers here? -->
          <img class="smallbimg" src=<%=review.photo_url%>>
        </a>
      <%= rating_for review, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
      <%="#{review.name.titleize} -- '#{review.title.titleize}' #{review.score}/10"%> <%="(#{review.user.email})"%>
    </li>
  </div>
  <%end%>
</ul>

app/views/bookreviews/new.html.erb
<div class="title">
  <h2>New Book Review</h2>
  <%=form_for @bookreview do |f| %>
    <%=f.label "Review Title"%><br>
    <%=f.text_field :title%><br>

    <%=f.label "Book Name"%><br>
    <%=f.text_field :name%><br>

    <%=f.label :score%><br>
    <%=f.select :score, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %><br>

    <%=f.label :text%><br>
    <%=f.text_area :text, rows: 10, cols: 60%><br>

    <%=f.submit%>
  <%end%>
</div>

app/views/bookreviews/show.html.erb
<!-- NHO: Really Liked the layout of the show page for all reviews!  -->
<h2 class="title">
  <%=@info.title%> by <%=@info.author%>
</h2>
<h3 class="title">
  <%=@bookreview.title%> [<%=@bookreview.score%>/10]
</h3>
<h4 class="title ital">
  By <%=@bookreview.user.email%> posted on: <%=@bookreview.created_at.strftime("%m/%d/%Y")%>  <%=@bookreview.created_at.strftime("at %I:%M%p")%>
</h4>
<div class="bookreviewimgtext">
  <img class="reviewimg" src="<%=@bookreview.photo_url%>">
  <p class="reviewtext"><%=@bookreview.text%>
</div>
<div class="titlelist">
  <h3>Other Books by <%=@info.author%></h3>
  <ol>
    <%@book_list.each do |book|%>
      <li><%=book['title']%> <%=book['publication_year']%></li>
    <%end%>
  </ol>
</div>
<hr>
<div class="title">
  <%if current_user == @bookreview.user%>
    <%=link_to "(Edit)", edit_bookreview_path(@bookreview)%>
    <%= link_to '(Delete)', bookreview_path(@bookreview), :method => :delete %>
  <%end%>
</div>
<hr>
<div class=centerimg>
  <ul>
    <li>
      <%if current_user%>
      Was this review helpful?
      <%elsif%>
      Log in to vote!
      <%end%>
      <%= rating_for @bookreview, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
    </li>
  </ul>
</div>


<hr>
<h2 class="title">
  Comments <%=link_to "(+)", "/bookreviews/#{@bookreview.id}/comments/new"%>
</h2>
<hr>
<%=render partial: "comments"%>