config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root :to => "reviews#index"
  resources :albumreviews, :except => ['create']
  resources :bookreviews do # NHO: Why did you need these custom route defintions and not resources :comments?
    get 'comments/new', to: 'comments#new_book_comment'
    post 'comments/post', to: 'comments#post_book_comment'
    delete 'comments/:id', to: 'comments#destroy_book_comment'
  end
  resources :reviews do
    resources :comments, :except => ['index', 'show']
  end
  get 'works/:id/show', to: 'works#show'  # NHO: What are purpose of these two custom routes for works?
  get 'works/:work_id/:work_index', to: 'works#select'
  resources :works do
    resources :albumreviews, :except => ['index', 'destroy' , 'show', 'edit', 'update']
  end
end

app/controllers/albumreviews_controller.rb
class AlbumreviewsController < ApplicationController
  # NHO: How could you DRY up this code? I see an opportunity for something along the lines of before_action :find_review
  #authenticate user
  before_action :authenticate_user!, except: [:show, :index]
  def index
    #all reviews with the category Album for the index page
    @reviews = Review.where(category: "Album")
  end
  def show
    @review = Review.find(params[:id]) #specific review to show
    @comments = @review.comments #comments belonging to that review
    @info = Work.find(@review.work_id) #the work being reviewed
    @tracks = RSpotify::Album.find(@info.unique_id).tracks #use spotify api to find tracks on the album being reviewed
  end
  def new
    #here the index is not the work id, it's actually
    #the index of the array of albums that the user has selected
    #we use this index to select a specific album from the list
    #there's definitely a better way to do this.
    @index = params[:work_id]
    #placeholder review
    @albumreview = Review.new
  end
  def create
    #here we relate the album that the user has chosen to the review
    #that is being generated
    work = Work.find(params[:work_id]).apidata
    #attach current user to the new review
    @review = current_user.reviews.create(review_params)
    #add some information from spotify api's response to the
    #review, this is probably not needed, it just allows me to
    #access some information from the review without going through
    #the api response elsewhere
    @review.update(category: "Album", work_id: params[:work_id], name: work["name"], photo_url: work['images'][0]['url'])
    redirect_to albumreview_path (@review)
  end
  def destroy
    #destroy an album review
    @albumreview = Review.find(params[:id])
    @albumreview.destroy
    redirect_to albumreviews_path
  end
  def edit
    #select a review to edit
    @albumreview = Review.find(params[:id])
  end
  def update
    #update and redirect based on params
    @albumreview = Review.find(params[:id])
    @albumreview.update(review_params)
    redirect_to albumreview_path(@albumreview)
  end
  private
  #strong params for album reviews
  def review_params
    params.require(:review).permit(:text, :title, :score)
  end
end

app/views/albumreviews/_comment.html.erb
<%@comments.each do |comment|%>
  <h3>
    <%=comment.user.email%> -- <%=comment.title%>
  </h3>
  <p>
    <%=comment.text%>
  </p>
  <%if current_user == @review.user || current_user == comment.user%>
    <%=link_to "(Remove Comment)", review_comment_path(@review, comment), :method => :delete%>
  <%end%>
  <hr>
<%end%>

app/views/albumreviews/edit.html.erb
<div class="title">
  <h2>Edit Album Review</h2>
  <%=form_for(@albumreview, url: albumreview_path) do |f| %>
    <%=f.label "Review Title"%><br>
    <%=f.text_field :title%><br>

    <%=f.label :score%><br>
    <%=f.select :score, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %><br>

    <%=f.label :text%><br>
    <%=f.text_area :text, rows: 3, cols: 30%><br>

    <%=f.submit%>
  <%end%>
</div>

app/views/albumreviews/index.html.erb
<h2 class="title">
  All Album Reviews
  <%=link_to "(+)", new_work_path%>
</h2>
<ul>
  <%@reviews.each do |review|%>
    <div class="albumlist">
      <li class>
        <a href=<%="/albumreviews/#{review.id}"%>> <!-- NHO: Could we utilize rails link_to helpers here? --> 
          <img class="smallaimg" src=<%=review.photo_url%>>
        </a>
        <%= rating_for review, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
        <%="#{review.name.titleize} -- '#{review.title}' #{review.score}/10"%>
        <%="(#{review.user.email})"%>
      </li>
    </div>
  <%end%>
</ul>

app/views/albumreviews/new.html.erb
<div class="title">
  <h2>New Album Review</h2>
  <%=form_for([@index, @albumreview], url: work_albumreviews_path) do |f| %>
    <%=f.label "Review Title"%><br>
    <%=f.text_field :title%><br>

    <%=f.label :score%><br>
    <%=f.select :score, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %><br>

    <%=f.label :text%><br>
    <%=f.text_area :text, rows: 10, cols: 60%><br>

    <%=f.submit%>
  <%end%>
</div>

app/views/albumreviews/show.html.erb
<h2 class="title">
  <%=@info.apidata["name"]%> by <%=@info.title%>
</h2>
<h3 class="title">
  <%=@review.title%> [<%=@review.score%>/10]
</h3>
<h4 class="title ital">
  By: <%=@review.user.email%> -- posted on: <%=@review.created_at.strftime("%m/%d/%Y")%>  <%=@review.created_at.strftime("at %I:%M%p")%>
</h4>
<div>
  <img  class ="reviewimg" src=<%=@review.photo_url%>>
  <div class= "tracks">
    <ol class = "tracklist">
    <%@tracks.each do |song|%>
      <li><%=song.name%></li>
    <%end%>
    </ol>
  </div>
</div>
<p class="reviewtext">
  <%=@review.text%>
</p>
<!-- NHO: We could utilize CanCanCan to help with this conditional -->
<%if current_user == @review.user%>
  <div class="title">
    <%=link_to "(Edit)", edit_albumreview_path(@review)%>
    <%= link_to '(Delete)', albumreview_path(@review), :method => :delete %>
  </div>
<%end%>

<hr>

<div class=centerimg>
  <ul>
    <li>
      <%if current_user%>
      Was this review helpful?
      <%elsif%>
      Log in to vote!
      <%end%>
      <%= rating_for @review, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
    </li>
  </ul>
</div>
<hr>
<h2 class="title">
  Comments <%=link_to "(+)", new_review_comment_path(@review)%>
</h2>
<hr>
<%=render partial: "comment"%>