config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root :to => "reviews#index"
  resources :albumreviews, :except => ['create']
  resources :bookreviews do # NHO: Why did you need these custom route defintions and not resources :comments?
    get 'comments/new', to: 'comments#new_book_comment'
    post 'comments/post', to: 'comments#post_book_comment'
    delete 'comments/:id', to: 'comments#destroy_book_comment'
  end
  resources :reviews do
    resources :comments, :except => ['index', 'show']
  end
  get 'works/:id/show', to: 'works#show'  # NHO: What are purpose of these two custom routes for works?
  get 'works/:work_id/:work_index', to: 'works#select'
  resources :works do
    resources :albumreviews, :except => ['index', 'destroy' , 'show', 'edit', 'update']
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # NHO: MoviesController?
  before_action :authenticate_user!, except: [:show, :index]
  def index
    #all movie reviews so they may be displayed on the index page
    @reviews = Review.where(category: "Movie")
  end
  def show
    #select specifc review for show page
    @review = Review.find(params[:id])
    @comments = @review.comments #comments related to that review
    @info = Moviework.find(@review.work_id) #the work table that the review is attached to
  end
  def new
    #placeholder review, renders form
    @review = Review.new
  end
  #create method for movie reviews
  def create
    @review = current_user.reviews.new(review_params) #create empty new review
    #query TMDB api for information about the input title
    movie_info = Tmdb::Search.movie("#{@review.name}")['results'][0]
    #find or create a new work based on the unique ID provided by TMDB
    @new_work = Moviework.find_or_create_by(unique_id: movie_info['id'])
    #if the work did not already exist and we just created it, it won't have a title
    #so I used the title column to check for this.  If we did create it, we fill it up
    #with information from the api call here.
    if (!@new_work.title)
      @new_work.update(overview: movie_info['overview'], medium: "Movie", release_date: movie_info['release_date'], unique_id: movie_info['id'], original_title: movie_info['original_title'], backdrop_path: movie_info['backdrop_path'], vote_avg: movie_info['vote_average'], poster_path: movie_info['poster_path'], title: movie_info['title'])
    end
    #add some information from the work to the review
    @review.update(work_id: @new_work.id, category: "Movie", photo_url: @new_work['poster_path'])
    #check to see if it saved properly
    if @review.save
      flash[:notice] = "Review was successfully created."
        redirect_to @review
    else
      flash[:alert] = "Review creation failed, likely missing a needed field."
      render :new
    end
  end
  #destroy a specific review
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end
  #select a review to edit
  def edit
    @review = Review.find(params[:id])
  end
  #update a review based on user params here
  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to review_path(@review)
  end
  private
  #strong params
  def review_params
    params.require(:review).permit(:text, :title, :score, :name, :category)
  end
  def work_params
    params.require(:review).permit(:name)
  end
end

app/views/reviews/_comment.html.erb
<div class="title">
  <%@comments.each do |comment|%>
    <h3>
      <%=comment.title%>
    </h3>
    <p>
      <%=comment.text%>
    </p>
    <p class="ital">
      By <%=comment.user.email%>
    </p>
    <%if current_user == @review.user || current_user == comment.user%>
      <%=link_to "(Remove Comment)", review_comment_path(@review, comment), :method => :delete%>
    <%end%>
    <hr>
  <%end%>
</div>

app/views/reviews/_form.html.erb
<div class ="title">
  <%=form_for @review do |f| %>
    <%=f.label "Review Title"%><br>
    <%=f.text_field :title%><br>

    <%=f.label "Movie Title"%><br>
    <%=f.text_field :name%><br>

    <%=f.label :score%><br>
    <%=f.select :score, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %><br>

    <%=f.label :text%><br>
    <%=f.text_area :text, rows: 10, cols: 60%><br>

    <%=f.submit%>
  <%end%>
</div>

app/views/reviews/edit.html.erb
<h2 class="title">Edit Review</h2>
<%=render partial: "form"%>

app/views/reviews/index.html.erb
<h2 class="title">
  All Movie Reviews
  <%=link_to "(+)", new_review_path%>
</h2>
<ul>
  <%@reviews.each do |review|%>
    <div class="movielist">
      <li>
        <a href=<%="/reviews/#{review.id}"%>> <!-- NHO: Could we utilize rails link_to helpers here? --> 
          <img class="smallmimg" src=https://image.tmdb.org/t/p/w780/<%=review.photo_url%>>
        </a>
        <%= rating_for review, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
        <%="#{review.name.titleize} -- '#{review.title.titleize}' #{review.score}/10"%> <%="(#{review.user.email})"%>
      </li>
    </div>
  <%end%>
</ul>

app/views/reviews/new.html.erb
<h2 class = "title">New Review</h2>
<%=render partial: "form"%>

app/views/reviews/show.html.erb
<div class="title">
  <h2>
    <%=@info["title"]%> / <%if @info["original_title"]%>
    <%=@info["original_title"]%>
    <%end%>
  </h2>
</div>
<div class="movieinfo">
  <ul class="nobullet">
    <li>Release Date: <%=@info['release_date']%></li>
    <li>The Movie DB score: <%=@info['vote_avg']%></li>
    <li>Summary: <%=@info['overview']%></li>
  </ul>
</div>
<div class="title">
  <h3>
    <%=@review.title%> [<%=@review.score%>/10]
  </h3>

  <h4 class="ital">
    By <%=@review.user.email%> posted on: <%=@review.created_at.strftime("%m/%d/%Y")%>  <%=@review.created_at.strftime("at %I:%M%p")%>
  </h4>
</div>
<div>
  <img class="reviewimg" src="https://image.tmdb.org/t/p/w780/<%=@review.photo_url%>">
  <p class="reviewtext"><%=@review.text%>
  <%if @info.backdrop_path%>
    <img class="backdrop" src="https://image.tmdb.org/t/p/w780/<%=@info.backdrop_path%>"/>
  <%end%>
</div>

<div class="title">
  <%if current_user == @review.user%>
    <hr>
    <%=link_to "(Edit)", edit_review_path(@review)%>
    <%= link_to '(Delete)', review_path(@review), :method => :delete %>
    <hr>
  <%end%>
</div>

<div class=centerimg>
  <ul>
    <li>
      <%if current_user%>
      Was this review helpful?
      <%elsif%>
      Log in to vote!
      <%end%>
      <%= rating_for @review, "Helpfulness", :disable_after_rate => false, star_path: '/images/ratyrate' %>
    </li>
  </ul>
</div>

<hr>
<h2 class="title">
  Comments <%=link_to "(+)", new_review_comment_path(@review)%>
</h2>
<hr>
<%=render partial: "comment"%>