config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root :to => "reviews#index"
  resources :albumreviews, :except => ['create']
  resources :bookreviews do # NHO: Why did you need these custom route defintions and not resources :comments?
    get 'comments/new', to: 'comments#new_book_comment'
    post 'comments/post', to: 'comments#post_book_comment'
    delete 'comments/:id', to: 'comments#destroy_book_comment'
  end
  resources :reviews do
    resources :comments, :except => ['index', 'show']
  end
  get 'works/:id/show', to: 'works#show'  # NHO: What are purpose of these two custom routes for works?
  get 'works/:work_id/:work_index', to: 'works#select'
  resources :works do
    resources :albumreviews, :except => ['index', 'destroy' , 'show', 'edit', 'update']
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youreview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'ratyrate.js.erb'%>
  <%= csrf_meta_tags %>
</head>
<!-- NHO: Disable turbolinks to fix star ratings -->
<body data-no-turbolink>
  <div class="bigdiv">
    <h1 class="title sitetitle">YouReview</h1>
    <div class="logindiv">
      <% if current_user %>
        <h3 class="login title"><%="#{current_user.email}"%>  <%= link_to '(Signout)', destroy_user_session_path, :method => :delete %></h3>
      <% else %>
        <h3 class="login title"><%= link_to 'Signup', new_user_registration_path %></h3>
        <h3 class="login title"><%= link_to 'Login', new_user_session_path %></h3>
      <% end %>
    </div>
    <ul class="nav">
      <li class="navli">
        <%=link_to "Movie Reviews", reviews_path, class: "navlink movielink"%>
      </li>
      <li class="navli">
        <%=link_to "Album Reviews", albumreviews_path, class: "navlink albumlink"%>
      </li>
      <li class="navli">
        <%=link_to "Book Reviews", bookreviews_path, class: "navlink booklink"%>
      </li>
    </ul>
    <p class="notice title"><%= notice %></p>
    <p class="alert title"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>